{
    "name": "pull-request",
    "on": {
        "push": { "branches": "main" },
        "pull_request": { "branches": "main" },
    },
    "jobs": {
        "linux": {
            "runs-on": "ubuntu-latest",
            "container": "vathpela/efi-ci:f36-x64",
            "steps": [
                { "uses": "actions/checkout@v2" },
                { "run": "meson build && ninja -C build" },
            ],
        },
    },
}
